{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rmfakecloud.fullname" . }}-config
  labels:
    {{- include "rmfakecloud.labels" . | nindent 4 }}
type: opaque
data:
  JWT_SECRET_KEY: {{ .Values.rmfakecloud.jwt_secret_key | default "" | b64enc }}
  RMAPI_HWR_APPLICATIONKEY: {{ .Values.rmfakecloud.rmapi_hwr_applicationkey | default "" | b64enc }}
  RMAPI_HWR_HMAC: {{ .Values.rmfakecloud.rmapi_hwr_hmac | default "" | b64enc  }}
  RM_SMTP_FROM: {{ .Values.rmfakecloud.rm_smtp_from | default "" | b64enc }}
  RM_SMTP_INSECURE_TLS: {{ .Values.rmfakecloud.rm_smtp_insecure_tls | default "" | b64enc }}
  RM_SMTP_PASSWORD: {{ .Values.rmfakecloud.rm_smtp_password | default "" | b64enc }}
  RM_SMTP_SERVER: {{ .Values.rmfakecloud.rm_smtp_server | default "" | b64enc }}
  RM_SMTP_USERNAME: {{ .Values.rmfakecloud.rm_smtp_username | default "" | b64enc }}
  RM_SMTP_HELO: {{ .Values.rmfakecloud.rm_smtp_helo | default "" | b64enc }}
  RM_SMTP_NOTLS: {{ .Values.rmfakecloud.rm_smtp_notls | default "" | b64enc  }}
  RM_SMTP_STARTTLS: {{ .Values.rmfakecloud.rm_smtp_starttls | default "" | b64enc }}
  RM_TRUST_PROXY: {{ .Values.rmfakecloud.rm_trust_proxy | default "" | b64enc }}
  STORAGE_URL: {{ .Values.rmfakecloud.storage_url | default "" | b64enc }}
  RM_HTTPS_COOKIE: {{ .Values.rmfakecloud.endifrm_https_cookie | default "" | b64enc }}
{{- end }}